services:
  postgresql:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_USER: zenycero
      POSTGRES_PASSWORD: zenycero
      POSTGRES_DB: twitterClone
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: